Ran bootstrap to include moab backend in the build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -876,6 +876,11 @@ LCRM_CPPFLAGS
 LCRM_LDFLAGS
 WITH_LCRM_TRUE
 WITH_LCRM_FALSE
+MOAB_LIBADD
+MOAB_CPPFLAGS
+MOAB_LDFLAGS
+WITH_MOAB_TRUE
+WITH_MOAB_FALSE
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1490,6 +1495,7 @@ Optional Packages:
   --with-tags[=TAGS]      include additional configurations [automatic]
   --with-slurm=PATH       Specify path to slurm installation
   --with-lcrm=PATH        Specify path to lcrm installation
+  --with-moab=PATH        Specify path to moab installation
 
 Some influential environment variables:
   CC          C compiler command
@@ -4605,7 +4611,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4608 "configure"' > conftest.$ac_ext
+  echo '#line 4614 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7564,11 +7570,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7567: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7573: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7571: \$? = $ac_status" >&5
+   echo "$as_me:7577: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7832,11 +7838,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7835: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7841: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7839: \$? = $ac_status" >&5
+   echo "$as_me:7845: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7936,11 +7942,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7939: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7945: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7943: \$? = $ac_status" >&5
+   echo "$as_me:7949: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10377,7 +10383,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10380 "configure"
+#line 10386 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10477,7 +10483,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10480 "configure"
+#line 10486 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12845,11 +12851,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12848: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12854: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12852: \$? = $ac_status" >&5
+   echo "$as_me:12858: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12949,11 +12955,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12952: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12958: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12956: \$? = $ac_status" >&5
+   echo "$as_me:12962: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14510,11 +14516,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14513: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14519: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14517: \$? = $ac_status" >&5
+   echo "$as_me:14523: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14614,11 +14620,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14617: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14623: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14621: \$? = $ac_status" >&5
+   echo "$as_me:14627: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16833,11 +16839,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16836: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16842: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16840: \$? = $ac_status" >&5
+   echo "$as_me:16846: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17101,11 +17107,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17104: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17110: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17108: \$? = $ac_status" >&5
+   echo "$as_me:17114: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17205,11 +17211,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17208: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17214: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17212: \$? = $ac_status" >&5
+   echo "$as_me:17218: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20444,7 +20450,241 @@ fi
 
 
 
-ac_config_files="$ac_config_files Makefile src/Makefile src/none/Makefile src/slurm/Makefile src/lcrm/Makefile"
+
+  MOAB_LIBADD="-lcmoab -lmoab -lminit -lpthread -lm -lmcom"
+  _x_ac_moab_dirs="/dpcs"
+  _x_ac_moab_libs="lib"
+
+
+# Check whether --with-moab was given.
+if test "${with_moab+set}" = set; then
+  withval=$with_moab; _x_ac_moab_dirs="$withval"
+     with_moab=yes
+else
+  with_moab=no
+fi
+
+
+  if test "$with_moab" = no; then
+    # Check for MOAB library in the default location.
+
+{ echo "$as_me:$LINENO: checking for MCCJobGetRemainingTime in -lmoab" >&5
+echo $ECHO_N "checking for MCCJobGetRemainingTime in -lmoab... $ECHO_C" >&6; }
+if test "${ac_cv_lib_moab_MCCJobGetRemainingTime+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmoab  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char MCCJobGetRemainingTime ();
+int
+main ()
+{
+return MCCJobGetRemainingTime ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_moab_MCCJobGetRemainingTime=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_moab_MCCJobGetRemainingTime=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_moab_MCCJobGetRemainingTime" >&5
+echo "${ECHO_T}$ac_cv_lib_moab_MCCJobGetRemainingTime" >&6; }
+if test $ac_cv_lib_moab_MCCJobGetRemainingTime = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBMOAB 1
+_ACEOF
+
+  LIBS="-lmoab $LIBS"
+
+fi
+
+  fi
+
+  if test "$ac_cv_lib_moab_MCCJobGetRemainingTime" != yes; then
+    { echo "$as_me:$LINENO: checking for moab installation" >&5
+echo $ECHO_N "checking for moab installation... $ECHO_C" >&6; }
+if test "${x_ac_cv_moab_dir+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+        for d in $_x_ac_moab_dirs; do
+          test -d "$d" || continue
+          test -d "$d/include" || continue
+          test -d "$d/include/moab" || continue
+          test -f "$d/include/moab/mapi.h" || continue
+          for bit in $_x_ac_moab_libs; do
+            test -d "$d/$bit" || continue
+
+            _x_ac_moab_libs_save="$LIBS"
+            LIBS="-L$d/$bit $MOAB_LIBADD $LIBS"
+            cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char MCCJobGetRemainingTime ();
+int
+main ()
+{
+return MCCJobGetRemainingTime ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  x_ac_cv_moab_dir=$d
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+            LIBS="$_x_ac_moab_libs_save"
+            test -n "$x_ac_cv_moab_dir" && break
+          done
+          test -n "$x_ac_cv_moab_dir" && break
+        done
+
+fi
+{ echo "$as_me:$LINENO: result: $x_ac_cv_moab_dir" >&5
+echo "${ECHO_T}$x_ac_cv_moab_dir" >&6; }
+  fi
+
+  if test "$with_moab" = no \
+     && test "$ac_cv_lib_moab_MCCJobGetRemainingTime" = yes; then
+    MOAB_CPPFLAGS=""
+    MOAB_LDFLAGS=""
+  elif test -n "$x_ac_cv_moab_dir"; then
+    MOAB_CPPFLAGS="-I$x_ac_cv_moab_dir/include"
+    MOAB_LDFLAGS="-L$x_ac_cv_moab_dir/$bit"
+  else
+    if test "$with_moab" = yes; then
+      { { echo "$as_me:$LINENO: error: moab is not in specified location!" >&5
+echo "$as_me: error: moab is not in specified location!" >&2;}
+   { (exit 1); exit 1; }; }
+    else
+      { echo "$as_me:$LINENO: WARNING: unable to locate moab installation" >&5
+echo "$as_me: WARNING: unable to locate moab installation" >&2;}
+    fi
+  fi
+
+
+
+
+
+
+
+if test -n "$x_ac_cv_moab_dir" || test "$ac_cv_lib_moab_MCCJobGetRemainingTime" = yes; then
+  WITH_MOAB_TRUE=
+  WITH_MOAB_FALSE='#'
+else
+  WITH_MOAB_TRUE='#'
+  WITH_MOAB_FALSE=
+fi
+
+
+
+ac_config_files="$ac_config_files Makefile src/Makefile src/none/Makefile src/slurm/Makefile src/lcrm/Makefile src/moab/Makefile"
 
 
 cat >confcache <<\_ACEOF
@@ -20582,6 +20822,13 @@ if test -z "${WITH_LCRM_TRUE}" && test -z "${WITH_LCRM_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"WITH_LCRM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"WITH_LCRM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WITH_MOAB_TRUE}" && test -z "${WITH_MOAB_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_MOAB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_MOAB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -21045,6 +21292,7 @@ do
     "src/none/Makefile") CONFIG_FILES="$CONFIG_FILES src/none/Makefile" ;;
     "src/slurm/Makefile") CONFIG_FILES="$CONFIG_FILES src/slurm/Makefile" ;;
     "src/lcrm/Makefile") CONFIG_FILES="$CONFIG_FILES src/lcrm/Makefile" ;;
+    "src/moab/Makefile") CONFIG_FILES="$CONFIG_FILES src/moab/Makefile" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -21272,11 +21520,16 @@ LCRM_CPPFLAGS!$LCRM_CPPFLAGS$ac_delim
 LCRM_LDFLAGS!$LCRM_LDFLAGS$ac_delim
 WITH_LCRM_TRUE!$WITH_LCRM_TRUE$ac_delim
 WITH_LCRM_FALSE!$WITH_LCRM_FALSE$ac_delim
+MOAB_LIBADD!$MOAB_LIBADD$ac_delim
+MOAB_CPPFLAGS!$MOAB_CPPFLAGS$ac_delim
+MOAB_LDFLAGS!$MOAB_LDFLAGS$ac_delim
+WITH_MOAB_TRUE!$WITH_MOAB_TRUE$ac_delim
+WITH_MOAB_FALSE!$WITH_MOAB_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 29; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 34; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
