Ran bootstrap

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -850,12 +850,6 @@ am__untar
 MAINTAINER_MODE_TRUE
 MAINTAINER_MODE_FALSE
 MAINT
-WANT_AIXSLURM_PROGRAM_TRUE
-WANT_AIXSLURM_PROGRAM_FALSE
-WANT_AIXSLURM_SPANK_PLUGIN_TRUE
-WANT_AIXSLURM_SPANK_PLUGIN_FALSE
-HAVE_AIX_TRUE
-HAVE_AIX_FALSE
 CC
 CFLAGS
 LDFLAGS
@@ -904,6 +898,12 @@ MOAB_CPPFLAGS
 MOAB_LDFLAGS
 WITH_MOAB_TRUE
 WITH_MOAB_FALSE
+WANT_AIXSLURM_PROGRAM_TRUE
+WANT_AIXSLURM_PROGRAM_FALSE
+WANT_AIXSLURM_SPANK_PLUGIN_TRUE
+WANT_AIXSLURM_SPANK_PLUGIN_FALSE
+HAVE_AIX_TRUE
+HAVE_AIX_FALSE
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -2790,51 +2790,6 @@ fi
 
 
 
-aix_64bit_mode=no
-using_aix=no
-case "$host" in
-	*-*-aix*)
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_AIX
-_ACEOF
-
-                  using_aix=yes
-                  LDFLAGS="$LDFLAGS -Wl,-brtl -Wl,-bexpfull"
-                  if test "$OBJECT_MODE" == "64" ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_AIX_64BIT
-_ACEOF
-
-                      aix_64bit_mode=yes
-                  fi
-        ;;
-esac
- if test "$using_aix" = yes && test "$aix_64bit_mode" = no && test "$slurm_available" = yes; then
-  WANT_AIXSLURM_PROGRAM_TRUE=
-  WANT_AIXSLURM_PROGRAM_FALSE='#'
-else
-  WANT_AIXSLURM_PROGRAM_TRUE='#'
-  WANT_AIXSLURM_PROGRAM_FALSE=
-fi
-
- if test "$using_aix" = yes && test "$aix_64bit_mode" = no && test "$slurm_available" = yes; then
-  WANT_AIXSLURM_SPANK_PLUGIN_TRUE=
-  WANT_AIXSLURM_SPANK_PLUGIN_FALSE='#'
-else
-  WANT_AIXSLURM_SPANK_PLUGIN_TRUE='#'
-  WANT_AIXSLURM_SPANK_PLUGIN_FALSE=
-fi
-
- if test "$using_aix" = yes; then
-  HAVE_AIX_TRUE=
-  HAVE_AIX_FALSE='#'
-else
-  HAVE_AIX_TRUE='#'
-  HAVE_AIX_FALSE=
-fi
-
-
 # Checks for programs.
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -4614,7 +4569,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4617 "configure"' > conftest.$ac_ext
+  echo '#line 4572 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7340,11 +7295,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7343: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7298: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7347: \$? = $ac_status" >&5
+   echo "$as_me:7302: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7608,11 +7563,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7611: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7566: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7615: \$? = $ac_status" >&5
+   echo "$as_me:7570: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7712,11 +7667,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7715: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7670: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7719: \$? = $ac_status" >&5
+   echo "$as_me:7674: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10009,7 +9964,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10012 "configure"
+#line 9967 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10109,7 +10064,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10112 "configure"
+#line 10067 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12445,11 +12400,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12448: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12403: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12452: \$? = $ac_status" >&5
+   echo "$as_me:12407: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12549,11 +12504,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12552: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12507: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12556: \$? = $ac_status" >&5
+   echo "$as_me:12511: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14110,11 +14065,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14113: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14068: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14117: \$? = $ac_status" >&5
+   echo "$as_me:14072: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14214,11 +14169,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14217: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14172: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14221: \$? = $ac_status" >&5
+   echo "$as_me:14176: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16401,11 +16356,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16404: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16359: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16408: \$? = $ac_status" >&5
+   echo "$as_me:16363: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16669,11 +16624,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16672: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16627: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16676: \$? = $ac_status" >&5
+   echo "$as_me:16631: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16773,11 +16728,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16776: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16731: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16780: \$? = $ac_status" >&5
+   echo "$as_me:16735: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20116,6 +20071,51 @@ fi
 
 
 
+aix_64bit_mode=no
+using_aix=no
+case "$host" in
+	*-*-aix*)
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AIX
+_ACEOF
+
+                  using_aix=yes
+                  LDFLAGS="$LDFLAGS -Wl,-brtl -Wl,-bexpfull"
+                  if test "$OBJECT_MODE" == "64" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_AIX_64BIT
+_ACEOF
+
+                      aix_64bit_mode=yes
+                  fi
+        ;;
+esac
+ if test "$using_aix" = yes && test "$aix_64bit_mode" = no && test "$slurm_available" = yes; then
+  WANT_AIXSLURM_PROGRAM_TRUE=
+  WANT_AIXSLURM_PROGRAM_FALSE='#'
+else
+  WANT_AIXSLURM_PROGRAM_TRUE='#'
+  WANT_AIXSLURM_PROGRAM_FALSE=
+fi
+
+ if test "$using_aix" = yes && test "$aix_64bit_mode" = no && test "$slurm_available" = yes; then
+  WANT_AIXSLURM_SPANK_PLUGIN_TRUE=
+  WANT_AIXSLURM_SPANK_PLUGIN_FALSE='#'
+else
+  WANT_AIXSLURM_SPANK_PLUGIN_TRUE='#'
+  WANT_AIXSLURM_SPANK_PLUGIN_FALSE=
+fi
+
+ if test "$using_aix" = yes; then
+  HAVE_AIX_TRUE=
+  HAVE_AIX_FALSE='#'
+else
+  HAVE_AIX_TRUE='#'
+  HAVE_AIX_FALSE=
+fi
+
+
 ac_config_files="$ac_config_files Makefile doc/Makefile doc/man/Makefile src/Makefile src/none/Makefile src/slurm/Makefile src/lcrm/Makefile src/moab/Makefile src/aixslurm/Makefile"
 
 
@@ -20222,27 +20222,6 @@ echo "$as_me: error: conditional \"MAINTAINER_MODE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${WANT_AIXSLURM_PROGRAM_TRUE}" && test -z "${WANT_AIXSLURM_PROGRAM_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"WANT_AIXSLURM_PROGRAM\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"WANT_AIXSLURM_PROGRAM\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${WANT_AIXSLURM_SPANK_PLUGIN_TRUE}" && test -z "${WANT_AIXSLURM_SPANK_PLUGIN_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"WANT_AIXSLURM_SPANK_PLUGIN\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"WANT_AIXSLURM_SPANK_PLUGIN\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${HAVE_AIX_TRUE}" && test -z "${HAVE_AIX_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"HAVE_AIX\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"HAVE_AIX\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -20282,6 +20261,27 @@ if test -z "${WITH_MOAB_TRUE}" && test -z "${WITH_MOAB_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"WITH_MOAB\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"WITH_MOAB\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WANT_AIXSLURM_PROGRAM_TRUE}" && test -z "${WANT_AIXSLURM_PROGRAM_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WANT_AIXSLURM_PROGRAM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WANT_AIXSLURM_PROGRAM\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WANT_AIXSLURM_SPANK_PLUGIN_TRUE}" && test -z "${WANT_AIXSLURM_SPANK_PLUGIN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WANT_AIXSLURM_SPANK_PLUGIN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WANT_AIXSLURM_SPANK_PLUGIN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_AIX_TRUE}" && test -z "${HAVE_AIX_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_AIX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_AIX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -20908,12 +20908,6 @@ am__untar!$am__untar$ac_delim
 MAINTAINER_MODE_TRUE!$MAINTAINER_MODE_TRUE$ac_delim
 MAINTAINER_MODE_FALSE!$MAINTAINER_MODE_FALSE$ac_delim
 MAINT!$MAINT$ac_delim
-WANT_AIXSLURM_PROGRAM_TRUE!$WANT_AIXSLURM_PROGRAM_TRUE$ac_delim
-WANT_AIXSLURM_PROGRAM_FALSE!$WANT_AIXSLURM_PROGRAM_FALSE$ac_delim
-WANT_AIXSLURM_SPANK_PLUGIN_TRUE!$WANT_AIXSLURM_SPANK_PLUGIN_TRUE$ac_delim
-WANT_AIXSLURM_SPANK_PLUGIN_FALSE!$WANT_AIXSLURM_SPANK_PLUGIN_FALSE$ac_delim
-HAVE_AIX_TRUE!$HAVE_AIX_TRUE$ac_delim
-HAVE_AIX_FALSE!$HAVE_AIX_FALSE$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -20922,6 +20916,12 @@ ac_ct_CC!$ac_ct_CC$ac_delim
 EXEEXT!$EXEEXT$ac_delim
 OBJEXT!$OBJEXT$ac_delim
 DEPDIR!$DEPDIR$ac_delim
+am__include!$am__include$ac_delim
+am__quote!$am__quote$ac_delim
+AMDEP_TRUE!$AMDEP_TRUE$ac_delim
+AMDEP_FALSE!$AMDEP_FALSE$ac_delim
+AMDEPBACKSLASH!$AMDEPBACKSLASH$ac_delim
+CCDEPMODE!$CCDEPMODE$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -20963,12 +20963,6 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
-am__include!$am__include$ac_delim
-am__quote!$am__quote$ac_delim
-AMDEP_TRUE!$AMDEP_TRUE$ac_delim
-AMDEP_FALSE!$AMDEP_FALSE$ac_delim
-AMDEPBACKSLASH!$AMDEPBACKSLASH$ac_delim
-CCDEPMODE!$CCDEPMODE$ac_delim
 am__fastdepCC_TRUE!$am__fastdepCC_TRUE$ac_delim
 am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
 GREP!$GREP$ac_delim
@@ -21003,6 +20997,12 @@ MOAB_CPPFLAGS!$MOAB_CPPFLAGS$ac_delim
 MOAB_LDFLAGS!$MOAB_LDFLAGS$ac_delim
 WITH_MOAB_TRUE!$WITH_MOAB_TRUE$ac_delim
 WITH_MOAB_FALSE!$WITH_MOAB_FALSE$ac_delim
+WANT_AIXSLURM_PROGRAM_TRUE!$WANT_AIXSLURM_PROGRAM_TRUE$ac_delim
+WANT_AIXSLURM_PROGRAM_FALSE!$WANT_AIXSLURM_PROGRAM_FALSE$ac_delim
+WANT_AIXSLURM_SPANK_PLUGIN_TRUE!$WANT_AIXSLURM_SPANK_PLUGIN_TRUE$ac_delim
+WANT_AIXSLURM_SPANK_PLUGIN_FALSE!$WANT_AIXSLURM_SPANK_PLUGIN_FALSE$ac_delim
+HAVE_AIX_TRUE!$HAVE_AIX_TRUE$ac_delim
+HAVE_AIX_FALSE!$HAVE_AIX_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
